# Generated by Django 4.0.4 on 2022-05-07 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('sets', models.IntegerField(default=0, verbose_name='Number of Sets')),
                ('reps', models.IntegerField(default=0, verbose_name='Number of Reps')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0, verbose_name='Weight')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise', verbose_name='Exercises')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.weight', verbose_name='Weight'),
        ),
    ]
