# Generated by Django 4.0.4 on 2022-05-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='weight',
        ),
        migrations.AddField(
            model_name='set',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Weight'),
        ),
    ]
