# Generated by Django 4.0.4 on 2022-05-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_remove_set_weight_set_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='set',
            field=models.ManyToManyField(related_name='sets', to='workout.set'),
        ),
    ]
