# Generated by Django 4.0.4 on 2022-05-08 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_exercise_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-dateTime']},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='workout',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
