# Generated by Django 4.0.4 on 2022-05-25 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_exercise_set'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='set',
        ),
        migrations.AddField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workout.exercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workout.workout'),
            preserve_default=False,
        ),
    ]
