# Generated by Django 4.0.4 on 2022-05-08 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_workout_options_remove_exercise_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weight',
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(default=0, verbose_name='Number of Reps')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.weight', verbose_name='Weight')),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.set', verbose_name='Set'),
        ),
    ]
