# Generated by Django 4.0.4 on 2022-05-08 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_remove_exercise_sets_set_exercise_remove_set_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-dateTime']},
        ),
    ]
