# Generated by Django 4.0.4 on 2022-06-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_workout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='set',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
