# Generated by Django 4.0.4 on 2022-06-16 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0006_remove_set_exercise_remove_set_workout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_number', models.IntegerField(verbose_name='Exercise Number')),
                ('rpe', models.IntegerField(blank=True, verbose_name='RPE')),
            ],
            options={
                'ordering': ['exercise_number'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Exercise Name')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(verbose_name='Set Number')),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('reps', models.IntegerField(verbose_name='Reps')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('created', models.DateTimeField(editable=False, verbose_name='Created')),
                ('modified', models.DateTimeField(verbose_name='Last Modified')),
                ('exercises', models.ManyToManyField(to='workout.exercise', verbose_name='Exercises')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercisetype', verbose_name='Exercise Type'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.ManyToManyField(to='workout.set', verbose_name='Sets'),
        ),
    ]
