# Generated by Django 4.0.4 on 2022-05-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_alter_workout_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(default=0, verbose_name='Reps')),
            ],
        ),
        migrations.RemoveField(
            model_name='set',
            name='reps',
        ),
        migrations.AddField(
            model_name='set',
            name='reps',
            field=models.ManyToManyField(to='workout.reps', verbose_name='Reps'),
        ),
    ]
