# Generated by Django 4.0.4 on 2022-05-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_reps_remove_set_reps_set_reps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='reps',
        ),
        migrations.AddField(
            model_name='set',
            name='reps',
            field=models.IntegerField(default=0, verbose_name='Number of Reps'),
        ),
        migrations.DeleteModel(
            name='Reps',
        ),
    ]
