# Generated by Django 4.0.4 on 2022-07-03 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_alter_workout_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-created']},
        ),
    ]
