# Generated by Django 4.0.4 on 2022-05-09 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_remove_set_reps_set_reps_delete_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workout', verbose_name='Workout'),
        ),
    ]
