# Generated by Django 4.0.6 on 2022-07-26 16:25

from django.db import migrations
from workout_tracker.common.util.helper import capitalize_sentence


def create_exercises(apps, schema_editor):
  upper_body_exercises = ['BARBELL BENCH PRESS', 'CRUNCH', 'LAT PULLDOWN', 'MILITARY PRESS', 'CHEST-SUPPORTED T-BAR ROW', 'CABLE FLYE', 'DUMBBELL SUPINATED CURL',
                          'SINGLE-ARM ROPE TRICEP EXTENSION', 'DUMBBELL INCLINE PRESS', 'REVERSE GRIP LAT PULLDOWN', 'DIP', 'BARBELL BENT OVER ROW',
                          'DUMBBELL LATERAL RAISE', 'SEATED FACE PULL', 'HAMMER CURL', 'SINGLE-ARM PULLDOWN', 'DUMBBELL SEATED SHOULDER PRESS', 'DUMBBELL ROW'
                          'EZ BAR CURL', 'HANGING LEG RAISE', 'NEUTRAL-GRIP PULLDOWN', 'CABLE LATERAL RAISE', 'REVERSE PEC DECK', 'SINGLE-ARM CABLE CURL',
                          'DUMBBELL SKULL CRUSHER', 'CABLE SEATED ROW', 'CABLE REVERSE FLYE', 'Cable Ab Curl', 'Ab Roller']

  lower_body_exercises = ['BACK SQUAT ', 'ROMANIAN DEADLIFT', 'BARBELL HIP THRUST', 'LEG EXTENSION', 'LYING LEG CURL', 'MACHINE SEATED HIP ABDUCTION',
                          'DEADLIFT', 'DUMBBELL WALKING LUNGE', 'SINGLE-LEG LEG EXTENSION', 'SINGLE-LEG LYING LEG CURL', 'SEATED LEG CURL',
                          'STANDING CALF RAISE', 'GOBLET SQUAT', 'DUMBBELL SINGLE-LEG HIP THRUST', 'LEG PRESS']
  
  ExerciseType         = apps.get_model('workout', 'ExerciseType')
  User                 = apps.get_model("auth", "User")
  root_user            = User.objects.get(id=1)

  for exercise in upper_body_exercises:
    capitalized_exercise   = capitalize_sentence(exercise)
    exercise_type, created = ExerciseType.objects.get_or_create(name=capitalized_exercise, user=root_user)
    exercise_type.save()

  for exercise in lower_body_exercises:
    capitalized_exercise   = capitalize_sentence(exercise)
    exercise_type, created = ExerciseType.objects.get_or_create(name=capitalized_exercise, user=root_user)
    exercise_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_exercisetype_user'),
    ]

    operations = [
      migrations.RunPython(create_exercises)
    ]
