# Generated by Django 4.0.6 on 2022-07-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_exercisetype_user'),
    ]

    operations = [
    ]
