# Generated by Django 4.0.6 on 2022-08-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0012_remove_exercise_rpe_exercise_lsrpe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisetype',
            name='description',
        ),
    ]
